### ISSUE TITLE
ICP流程测试需求Issue

### ISSUE THREAD

**Issue by WangWanyue** [WangWanyue/sibbay-ai#3]
ICP操作issue @maohuaming

**Comment by maohuaming** [comment]
@WangWanyue 不需要打操作标签，规则中和流程图中没有提及的事，不要做。

**Comment by WangWanyue** [comment]
@maohuaming 好的，明确

**Comment by WangWanyue** [comment]
@maohuaming  deadline: 2018-03-23 size:1

**Comment by WangWanyue** [comment]
@maohuaming 已经关闭
