### ISSUE TITLE
小白社区ICP认证之BUG Issue

### ISSUE THREAD

**Issue by WangWanyue** [WangWanyue/sibbay-ai#6]
小白社区ICP认证之BUG Issue @maohuaming

**Comment by maohuaming** [comment]
@WangWanyue 请设置deadline。

**Comment by WangWanyue** [comment]
@maohuaming deadline: 2018-03-23 size:1

**Comment by maohuaming** [comment]
@WangWanyue 请按认证规则提交文件，创建pr。

**Comment by maohuaming** [comment]
@WangWanyue commit的名称有错误，你再看下。开发需求和修复缺陷的名称是不同的。
